Doing mathematics operations same as set theory in arrays is NumPy set operation.

Remove duplicates
Find common or different values
Combine arrays without repetition

# Examples

In [2]:
#easy
import numpy as np

a = np.array([1, 2, 2, 3, 4, 4, 5])
print(np.unique(a))  

[1 2 3 4 5]


In [2]:
#intermediate
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

print("Union:", np.union1d(a, b))
print("Intersection:", np.intersect1d(a, b))
print("A - B:", np.setdiff1d(a, b))
print("Symmetric Diff:", np.setxor1d(a, b))


Union: [1 2 3 4 5 6]
Intersection: [3 4]
A - B: [1 2]
Symmetric Diff: [1 2 5 6]


In [3]:
#hard
a = np.array([10, 20, 30, 40])
b = np.array([20, 30])

print(np.in1d(a, b))  

print(np.isin(a, [10, 99]))

[False  True  True False]
[ True False False False]


C:\Users\Acer\AppData\Local\Temp\ipykernel_4196\2155899775.py:5: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  print(np.in1d(a, b))


# Exercises

In [5]:
# Q1: Union of [1,2,3] and [2,3,4,5]

x = [1,2,3]
y = [2,3,4,5]

print(np.union1d(x,y))

[1 2 3 4 5]


In [ ]:
z = [4, 4, 2, 1, 3, 1, 2]

print(np.unique(z)) #by default sorted

[1 2 3 4]


In [7]:
# Q2: Find items only in first array [10,20,30] but not in second [20,40]

c = [10,20,30]
d = [20,40]

print("Items only in 1st array but not in 2nd array are", np.setdiff1d(c,d))

Items only in 1st array but not in 2nd array are [10 30]


In [8]:
# Q3: Are elements of [3, 5] present in [1,2,3,4,5]

e = [3,5]
f = [1,2,3,4,5]

print(np.isin(e,f))

[ True  True]


Mini Project: Email List Cleaner

In [9]:
subscribed = np.array(["a@gmail.com", "b@gmail.com", "c@gmail.com"])
unsubscribed = np.array(["b@gmail.com"])

cleaned = np.setdiff1d(subscribed, unsubscribed)
print("Cleaned Email List:", cleaned)

Cleaned Email List: ['a@gmail.com' 'c@gmail.com']


Mini Project: Data Cleanup Utility

In [7]:
np.random.seed(42)

marketing_users = np.random.randint(1000,2000,100)
# print("Marketing Users:\n",marketing_users)

website_users = np.random.randint(1000,2000,80)
# print("Website Users\n",website_users)

clean_marketing_users = np.unique(marketing_users)
# print("Clean List of Marketing Users:\n",clean_marketing_users)

clean_website_users = np.unique(website_users)
# print("Clean List of Website Users:\n",clean_website_users)

common_users = np.intersect1d(clean_marketing_users, clean_website_users)
# print("Common Users:\n",common_users)

marketing_exclusive_users = np.setdiff1d(clean_marketing_users, clean_website_users)
# print("Marketing Exclusive Users:\n",marketing_exclusive_users)

combine_users = np.union1d(clean_marketing_users, clean_website_users)
# print("Union of the Users:\n",combine_users)


print("Total Unique Marketing Users:", len(clean_marketing_users))
print("Total Unique Website Users:", len(clean_website_users))
print("Common Users:", len(common_users))
print("Marketing-Only Users:", len(marketing_exclusive_users))
print("Total Unique Users Across Both Lists:", len(combine_users))

Total Unique Marketing Users: 94
Total Unique Website Users: 78
Common Users: 6
Marketing-Only Users: 88
Total Unique Users Across Both Lists: 166
