This is important for performance, memory efficiency and data integrity.

View is the reference of the original array. If we make changes in view then original array also change.

Copy is object created from the exact same data of original array. Change in copy does not affect original array.

# Examples

In [ ]:
# easy
import numpy as np
a = np.array([1, 2, 3])
b = a.view()
b[0] = 100
print(a)

[100   2   3]


In [ ]:
# intermediate
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


In [7]:
# hard
a = np.arange(9).reshape(3, 3)
print(a)
b = a[::2, ::2]
b[0, 0] = 999
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[999   1   2]
 [  3   4   5]
 [  6   7   8]]


# Exercises

In [9]:
# Create a 1D array and create a view. Modify the view and observe what changes.

np.random.seed(42)
a = np.random.randint(1,11,10)
print(a)
b = a.view()
b[0] = 100
print(a)

[ 7  4  8  5  7 10  3  7  8  5]
[100   4   8   5   7  10   3   7   8   5]


In [13]:
# Create a 2D array, make a copy of a slice, modify the copy. Prove original remains same.

x = np.arange(16).reshape(4, 4)
print(x,"\n")

y = x.copy()
y[0] = 100

print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [14]:
# Make a function that takes a NumPy array, returns both its view and copy. Test it with modification.

def get_view_and_copy(array):
    view_array = array.view()
    copy_array = array.copy()
    return view_array, copy_array

np.random.seed(42)
original_array = np.random.randint(1,100,10)

view_arr, copy_arr = get_view_and_copy(original_array)

view_arr[0] = 199
copy_arr[0] = 199

print("Original Array:",original_array)
print("View Array:", view_arr)
print("Copy Array:", copy_arr)

print("View shares memory", view_arr.base is original_array)
print("Copy shares memory", copy_arr.base is original_array)

Original Array: [199  93  15  72  61  21  83  87  75  75]
View Array: [199  93  15  72  61  21  83  87  75  75]
Copy Array: [199  93  15  72  61  21  83  87  75  75]
View shares memory True
Copy shares memory False


Mini Project: Array Audit Tool

Goal: Create a tool that checks if an array is a view or copy and performs safe modifications.

Instructions:

Create a base array

Take a slice (view)

Create a full copy

Print .base to check view status

Modify both, show changes

Conclude: Which one is safe for operations?

In [ ]:
# creating base array
audit = np.random.randint(1,100,10)

# taking a slice
base_array = audit[0:5]

# copying original array
copy_array = audit.copy()

# printing .base to check view status
print(base_array.base is audit)
print(copy_array.base is audit)

# modifying both arrays
base_array[0] = 299
copy_array[0] = 299

# showing modified arrays
print(base_array)
print(copy_array)

True
False
[299  42  92  60  80]
[299  42  92  60  80  15  62  62  47  62]
