using np.ix_()

In [2]:
import numpy as np

arr = np.arange(1, 17).reshape(4, 4)

print(arr,"\n")

rows = [1,3]
cols = [0,2]


submatrix = arr[np.ix_(rows, cols)]
print(submatrix,"\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[[ 5  7]
 [13 15]] 



using np.newaxis

In [6]:
a = np.array([4,5,6,7,8,9,0])

row_vec = a[np.newaxis, :]
col_vec = a[:, np.newaxis]

print(row_vec,"\n\n", col_vec)

[[4 5 6 7 8 9 0]] 

 [[4]
 [5]
 [6]
 [7]
 [8]
 [9]
 [0]]


using advance indexing extract only row 1 and 3

In [ ]:
arr1 = np.arange(1,21).reshape(4,5)
print(arr1, "\n")

# Using advanced indexing, extract only rows 1 and 3
row = [1,3]
submatrix1 = arr1[np.ix_(row)]
print(submatrix1, "\n")

# Extract only columns 0, 2, and 4 from all rows
column = [0, 2, 4]
col_matrix = arr1[:, column]
print(col_matrix,"\n")

# Extract submatrix from rows 0, 2 and columns 1, 3
r = [0, 2]
c = [1, 3]

new_matrix = arr1[np.ix_(r,c)]
print(new_matrix,"\n")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

[[ 6  7  8  9 10]
 [16 17 18 19 20]] 

[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]] 

[[ 2  4]
 [12 14]] 



Convert 1D array to Row and Column Vector using np.newaxis

In [24]:
bArray = np.array([20,40,50])

row_vector = bArray[np.newaxis,:]
column_vector = bArray[:, np.newaxis]
print(row_vector, "\n", column_vector, "\n")

[[20 40 50]] 
 [[20]
 [40]
 [50]] 



Create an addition table using broadcasting:

In [27]:
row = np.array([1, 2, 3])
col = np.array([10, 20, 30, 40])

addition = row[:, np.newaxis] + col
print(addition)

[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


Compare Temperatures Between Cities Kathmandu & Biratnagar (Real Dataset Based)

In [46]:
dataset = np.genfromtxt('rainfall_data.csv', delimiter=',', names=True, dtype=None, encoding='utf-8')
print(dataset.dtype.names, "\n")
print(dataset)

kathmandu_temp = dataset['Temperature_C'][dataset['City'] == 'Kathmandu']
biratnagar_temp = dataset['Temperature_C'][dataset['City'] == 'Biratnagar']

print(f"Temperatures in the Kathmandu for 3 days are {kathmandu_temp}")
print(f"Temperatures in the Biratnagar for 3 days are {biratnagar_temp}")

import numpy.ma as ma
masking_ktm = ma.masked_invalid(kathmandu_temp) # masking nan value in temperature column
masking_birat = ma.masked_invalid(biratnagar_temp) # masking nan value in temperature column

adding_both_cities = masking_ktm[:, np.newaxis] + masking_birat
print(adding_both_cities)
avg_temp = ma.mean(adding_both_cities)
print(avg_temp)

('Date', 'City', 'State', 'Rainfall_mm', 'Temperature_C', 'Humidity_', 'Weather_Type') 

[('2024-06-01', 'Kathmandu', 'Bagmati', 12.5, 22. , 85., 'Rain')
 ('2024-06-02', 'Nepalgunj', 'Lumbini',  0. , 35.2, 40., 'Clear')
 ('2024-06-03', 'Biratnagar', 'Koshi',  3.4, 28.3, 60., 'Cloudy')
 ('2024-06-04', 'Kathmandu', 'Bagmati',  8.2, 21.7, 88., 'Rain')
 ('2024-06-05', 'Nepalgunj', 'Lumbini',  0. , 36. , 38., 'Clear')
 ('2024-06-06', 'Biratnagar', 'Koshi',  0. , 30.1, 55., 'Sunny')
 ('2024-06-07', 'Kathmandu', 'Bagmati',  nan, 23.5, 70., 'Cloudy')
 ('2024-06-08', 'Nepalgunj', 'Lumbini',  1.5,  nan, 45., 'Drizzle')
 ('2024-06-09', 'Biratnagar', 'Koshi',  2.7, 27.4, nan, 'Rain')]
Temperatures in the Kathmandu for 3 days are [22.  21.7 23.5]
Temperatures in the Biratnagar for 3 days are [28.3 30.1 27.4]
[[50.3 52.1 49.4]
 [50.0 51.8 49.099999999999994]
 [51.8 53.6 50.9]]
51.0
