In [1]:
import numpy as np

# Step 1: Create a sample grayscale image (10x10) with values 0-255
image = np.random.randint(0, 256, (10, 10)).astype(np.float32)
print("Original Image:\n", image)

# Step 2: Define kernels
blur_kernel = np.ones((3, 3)) / 9  # Simple averaging kernel
edge_kernel = np.array([[ -1, -1, -1],
                        [ -1,  8, -1],
                        [ -1, -1, -1]])  # Laplacian edge detection

# Step 3: Implement convolution function
def convolve2d(image, kernel):
    kernel_height, kernel_width = kernel.shape
    img_height, img_width = image.shape

    # Calculate padding sizes
    pad_h = kernel_height // 2
    pad_w = kernel_width // 2

    # Pad the image with zeros on border
    padded_image = np.pad(image, ((pad_h, pad_h), (pad_w, pad_w)), mode='constant')

    # Prepare output array
    output = np.zeros_like(image)

    # Slide the kernel over every pixel of the image
    for i in range(img_height):
        for j in range(img_width):
            # Extract current region
            region = padded_image[i:i + kernel_height, j:j + kernel_width]
            # Element-wise multiplication and sum
            output[i, j] = np.sum(region * kernel)

    return output

# Step 4: Apply filters
blurred_image = convolve2d(image, blur_kernel)
edges_image = convolve2d(image, edge_kernel)

# Step 5: Show results (text output)
print("\nBlurred Image:\n", blurred_image)
print("\nEdge Detection Image:\n", edges_image)

Original Image:
 [[ 80. 176. 235. 213.  15. 197. 178. 255. 249. 154.]
 [120. 190. 236.  64.  77. 174.  15. 225. 245.  70.]
 [236. 160.  23. 103. 253. 246. 241. 103. 194.  55.]
 [139. 208. 185. 128.  72.  49. 109.  83.  86.  81.]
 [208. 163. 137. 176. 170.  69. 135. 204. 102. 151.]
 [103. 217.  57.  85. 127. 227. 136. 181.  42.  44.]
 [239.  53. 178.  38.  32.  28. 154.   5.  87. 115.]
 [248. 182. 142.  68. 211. 212. 111. 212. 191. 230.]
 [165. 187.  68.   5. 184.  35. 166.  54.  93.   3.]
 [225. 147. 112. 161. 178. 251. 163.  81.  21. 218.]]

Blurred Image:
 [[ 62.88889  115.22222  123.77778   93.333336  82.22222   72.888885
  116.       129.66667  133.11111   79.77778 ]
 [106.888885 161.77777  155.55556  135.44444  149.11111  155.11111
  181.55556  189.44444  172.22223  107.44444 ]
 [117.       166.33333  144.11111  126.77778  129.55556  137.33333
  138.33333  144.55556  126.888885  81.22222 ]
 [123.77778  162.11111  142.55556  138.55556  140.66667  149.33333
  137.66667  139.66667  1